schema: fds-token-group/v1
imports:
- ../../../seed/color.yml
- ./brand.yml
- ./amber.yml
- ./yellow.yml
- ./yellow-green.yml
- ./green.yml
- ./teal.yml
- ./blue.yml
- ./indigo.yml
- ./purple.yml
- ./magenta.yml
- ./red.yml
